### ISSUE TITLE
Галочка в конце урока "Выполнено" нуждается в тексте

### ISSUE THREAD

**Issue by Freika** [codenamecrud/codenamecrud#54]
Как должно быть:

![](http://take.ms/jOLFS)

Как есть сейчас:

![](http://take.ms/Y7Hoy)

**Comment by Freika** [comment]
@dipiash https://github.com/codenamecrud/codenamecrud/blob/master/spec/features/progress_bar_spec.rb#L43 этот тест красный после соединения твоего ПРа, посмотришь, что там произошло?

**Comment by dipiash** [comment]
Да, посмотрю.

**Comment by dipiash** [comment]
Тоже можно закрыть задачу.
