### ISSUE TITLE
Переход к следующему уроку

### ISSUE THREAD

**Issue by Freika** [codenamecrud/codenamecrud#57]
![](http://take.ms/Nqysv)

**Comment by dipiash** [comment]
А также, из обсуждений в ПР:

> Но, на данный момент, так как уроки можно выполнять в рандомном порядке, то к примеру:
> 1 урок подвержден
> 2 урок подтвержден
> 3 урок не подтвержден
> 4 урок подтвержден
> То ссылка будет вести на 5й.

Необходимо добавить блокировку "отключения средних уроков".
