### ISSUE TITLE
Тест на консистентность данных

### ISSUE THREAD

**Issue by Freika** [codenamecrud/codenamecrud#60]
Нам нужно сделать тест, которые будет выполнять следующую последовательность действий:
- Загружать сиды
- Выполнять команду `rake curriculum:content_update`
- Проходить по каждой созданной странице и убеждаться, что она отдает статус 200, содержит контент и что этот контент эквивалентен тому, что содержится на гитхабе по адресу, указанному в seeds для каждой из страниц.

**Comment by sdilshod** [comment]
Если команда `rake curriculum:content_update` обновляет контент уроков из репо, в чем смысл проверять на эквивалентность контентов? @Freika

**Comment by Freika** [comment]
В том, чтобы точно знать, что содержимое всех уроков было загружено без ошибок. Есть другие идеи?

**Comment by sdilshod** [comment]
Получается попутно проверяем и работу таска, понятно
