### ISSUE TITLE
Статус выполнения урока

### ISSUE THREAD

**Issue by Freika** [codenamecrud/codenamecrud#70]
@dipiash 

![](http://take.ms/Kb3WT)

Здесь у нас появляется окошко, которое никак не закрыть и оно не исчезает. Я думаю, галочку рядом с названием урока стоит вообще убрать и оставить только внутри самого урока, а в списке уроков показывать read-only статус (чтобы нельзя было его изменить). Ну и окошко это тоже убрать нужно будет.

**Comment by dipiash** [comment]
Ок. Посмотрю.

**Comment by dipiash** [comment]
Навереное, задачу можно закрыть?

**Comment by Freika** [comment]
Да, спасибо, не углядел :)
