### ISSUE TITLE
Список литературы

### ISSUE THREAD

**Issue by makketagg** [codenamecrud/codenamecrud#88]
Любой курс сопровождается списком полезной литературы, так как никакой курс не может полностью покрыть вопросы учащегося. Можно рассмотреть это как прикрепленный список к курсу или глобальный список полезной литературы на сайте.

**Comment by Freika** [comment]
> никакой курс не может полностью покрыть вопросы учащегося

Именно поэтому в начале курса есть урок, в котором говорится о важности уметь пользоваться поисковиком :)

По теме: да, идея хорошая. Стоит заняться, когда закончим перевод оставшихся уроков.
